version: "3.8"

services:
    # PostgreSQL Database
    postgres:
        image: postgres:15-alpine
        container_name: toilet-finder-db
        environment:
            POSTGRES_DB: toilet_finder
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
        networks:
            - toilet-finder-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Backend API
    backend:
        build:
            context: ../backend
            dockerfile: ../infra/Dockerfile.backend
        container_name: toilet-finder-backend
        environment:
            NODE_ENV: development
            PORT: 8000
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: toiletfinder
            DB_USER: postgres
            DB_PASSWORD: password
            DB_MAX_CONNECTIONS: 20
            DB_IDLE_TIMEOUT: 30000
            DB_CONNECTION_TIMEOUT: 2000
            CORS_ORIGIN: http://localhost:3000
            USE_TOKYO_API: true
            ENABLE_AUTO_SYNC: true
        ports:
            - "8000:8000"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - toilet-finder-network
        volumes:
            - ../backend:/app
            - /app/node_modules
        command: npm run dev

    # Frontend Application
    frontend:
        build:
            context: ../frontend
            dockerfile: ../infra/Dockerfile.frontend
        container_name: toilet-finder-frontend
        environment:
            VITE_API_BASE_URL: http://localhost:8000/api
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - toilet-finder-network
        volumes:
            - ../frontend:/app
            - /app/node_modules
        command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
    toilet-finder-network:
        driver: bridge

volumes:
    postgres_data:
